baseURL: https://anetas-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website - Aneta Gajdzinska
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     I am creating this website as a project for my university
    title: Hi, my name is Aneta 
  blog: {}
  contact:
    address: 
      - city: London
        country: United Kingdom
        street: Baker Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: xxx@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: +44 0000000
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: #Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
       # label: Twitter
       # url: https://www.twitter.com
     # - icon: fa-facebook
      #  label: Facebook
      #  url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/nettagatta/
      - icon: fa-github
        label: GitHub
        url: https://github.com/AnetaGaj
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/aneta-gajdzinska/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
       # url: blogs/ipsum
     # - name: Elements
      #  url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Aneta's website
        title: Hello and welcome! 
        url: blogs/risk_return
      - image: pic02.jpg
        subtitle: Take a break
        title: My thoughts
        url: blogs/tempus
      - image: spices.jpg
        subtitle: Professor's project
        title: Project 1
        url: blogs/risk_return
      - image: horse.jpg
        subtitle: Horse riding
        title: Sports
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: ---
        title: Project 2 
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: ---
        title: Project 3
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Let's dive in"
    title: A bit more...
    url: blogs
